### ISSUE TITLE
Simple documentation

### ISSUE THREAD

**Issue by Igorbek** [Igorbek/CodeContracts.MSBuild#12]
Need to write simple documentation in `README`, such as:
- Installation
- How to use in VS 2017
- MSBuild properties
- Best practices
- Links to original project (Microsoft Contracts)

**Comment by kkm000** [comment]
One thing you probably want to consider is that Contracts are dead. The project cannot be even resurrected with its current code base, because it relied on the compiler behavior, IL code patterns emitted by compilers, and this was in the times of C# 2.0. It does not work with Tasks/`async`s. It still does somewhat work with C# 6, but completely broken with C# 7. And there is nobody around to work on it. The main researcher behind it, Francesco Logozzo, has left Microsoft years ago.

So the only missing documentation, I believe, is the relation between the checkboxes on the property page of VS extension thatdoes not work any more and `CodeContracts...` MSBuild properties. Nobody should *begin* using Contracts, and the whole point now is only to support anyone who does before they can wean themselves off it, unfortunately. And they already know what they are doing.

**Comment by Igorbek** [comment]
Yes, unfortunately it is so true.

**Comment by Igorbek** [comment]
Simple docs are in readme.md now.
