### ISSUE TITLE
What is this package?

### ISSUE THREAD

**Issue by w1ld** [Igorbek/CodeContracts.MSBuild#6]
Thank you for releasing this package. 

What is the aim of this package and how it differs from the official one (https://github.com/Microsoft/CodeContracts) ? Wanting to build CC under VS2017. That package seems to solve this. How does it differ from this package - https://github.com/WiseTechGlobal/CodeContracts/releases ?

**Comment by Igorbek** [comment]
@w1ld thank you for asking.
It is not a replacement for the official package, it is meant to complement it by providing MSBuild drop-in integration. This project just repacks the CC and injects required build steps for smother integration with build/CI systems that do not have the CC preinstalled.
Ideally, it should be moved to the official repo.
The nearest idea is to make usage of official package instead of including binaries explicitly.
